Feature: 전체 조회, 개별 조회 기능 추가
moduMoyeora/moyeora-backend pull request #1
Opened 2024-12-09 07:58 UTC by YoungJaeIm

### 변경 사항

1. 게시판 별 게시글 목록 전체 조회 기능 추가
2. 게시글 개별 조회 기능 추가

2024-12-09 09:15 UTC, subinggrae commented
1. 파일 네이밍 컨벤션을 상의하고 통일하면 좋겠습니다.
처음 프로젝트 생성해주신 것을 기반으로 제가 작업중인 프로젝트 구조는 이런 상태입니다.
```
│  app.ts
│
├─config
│      db.ts
│
├─controllers
│      postController.ts
│
├─models
│      postModel.ts
│
├─routes
│      postRoute.ts
│
├─services
│      postService.ts
│
└─type
    └─interface
            postInterface.ts
```

2. posts에 접근하는 경로를 /boards/:boardId/posts로 통일하자는 의견에는 어떻게 생각하시나요?
작업물에는 /posts로  작업하신 걸로 보입니다.

2024-12-10 10:18 UTC, junho2408 approved these changes

2024-12-10 11:25 UTC, ksy90101 requested changes

2024-12-10 11:25 UTC, ksy90101 commented on src/controllers/boardController.ts
> +            });
왜 posts가 0개인데 게시판을 찾을수 없는건가요?
게시판이 있지만, 글이 없을수도 있지 않나요?
에러 상황이 아닌거 같습니다. 에러 처리를 더 정확히 해주시면 좋을거 같습니다.

2024-12-10 11:25 UTC, ksy90101 commented on src/controllers/boardController.ts
> +    }
이건 없어도 될듯합니다.

2024-12-10 11:25 UTC, ksy90101 commented on src/controllers/postController.ts
> +        const post = await getPostById(Number(id));
해당 부분에서 에러를 던지고, catch를 이용해 404 처리를 해주세요.

2024-12-10 11:25 UTC, ksy90101 commented on src/models/boardModel.ts
> +        LIMIT ? OFFSET ?
페이지네이션에는 offset방식과 cursor 방식이 있습니다.
이 두가지를 비교해보시고, 왜 offset을 선택하셨는지 이야기를 해주세요.

2024-12-10 11:25 UTC, ksy90101 commented on src/models/boardModel.ts
> +        LIMIT ? OFFSET ?
다른 백엔드 개발자 분들에게도 . 이거 전해주세요. 같이 토론하셔도 좋습니다.

2024-12-10 11:25 UTC, ksy90101 commented on src/models/boardModel.ts
> +        FROM post
이건 post가 메인인데 board에 있는게 맞을까요?

2024-12-10 11:25 UTC, ksy90101 commented on src/validators/postValidator.ts
> +    ];
주석인 이유가 있나요?

2024-12-12 02:30 UTC, YoungJaeIm commented on src/models/boardModel.ts
> +        LIMIT ? OFFSET ?
프로젝트의 데이터 용량이 크지 않고, 게시판 페이지 형식에는 특정 페이지 이동 기능 구현이 되어야 한다고 생각해 
offset이 cursor방식보다 적절하다 판단했습니다. 토의 결과도 이와 같습니다.

2024-12-12 02:31 UTC, merged