Feat/유저 프로필 조회, 수정 API 추가
moduMoyeora/moyeora-backend pull request #11
Opened 2024-12-17 15:00 UTC by junho2408

- 유저 프로필 조회
- 유저 프로필 수정
- member table에 관련 컬럼을 추가해서 작업했습니다

2024-12-17 15:37 UTC, ksy90101 requested changes

2024-12-17 15:37 UTC, ksy90101 commented on src/controllers/userController.ts
> +  const { field, value } = req.body as unknown as check_duplicate;
as unknown 해당 코드가 추가되어야 하는 이유가 무엇인가요?

2024-12-17 15:37 UTC, ksy90101 commented on src/controllers/userController.ts
자기 자신의 profile을 조회해야하고, 자기자신의 profile만 수정해야 하지 않나요?
인가가 제대로 안되어 있어요.
혹시 못하는 이유가 있나요?

2024-12-18 07:45 UTC, junho2408 commented on src/controllers/userController.ts
> +  const { field, value } = req.body as unknown as check_duplicate;
다시 점검해보니 불필요한 부분이라 제거했습니다.

2024-12-18 07:55 UTC, junho2408 commented on src/controllers/userController.ts
놓치고 있었네요... 고려해서 추가로 작업하도록 하겠습니다!!

2024-12-19 05:26 UTC, merged