ci: PR validation 워크플로우 추가
moduMoyeora/moyeora-backend pull request #7
Opened 2024-12-13 05:47 UTC by subinggrae

## 📝 작업 내용
github action 추가하였습니다.

## ✨ 주요 변경사항
- PR이 업데이트 되면 lint -> typecheck & build 작업 실행합니다.

2024-12-13 07:59 UTC, ksy90101 requested changes

2024-12-13 07:59 UTC, ksy90101 commented on .github/workflows/pr-validation.yml
> +      - run: npm install
```suggestion
      - run: npm ci
```

2024-12-13 07:59 UTC, ksy90101 commented on .github/workflows/pr-validation.yml
> +jobs:
node 설치가 필요.

2024-12-15 13:59 UTC, junho2408 approved these changes

2024-12-16 07:21 UTC, merged